name: monorepo/check

on:
  # Runs on pull request events:       
  pull_request: {}              

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        
    runs-on: ${{ matrix.os }}

    name: Type Check
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Common Setup"
        uses: ./.github/actions/common-setup

      - name: Run Type Check
        run: bun run check:all