name: monorepo/test

on:
  # Runs on pull request events:       
  pull_request: {}

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        
    runs-on: ${{ matrix.os }}

    name: Run Tests
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        
      - name: "Common Setup"
        uses: ./.github/actions/common-setup

      - name: Run Format Check
        run: bun run test:all